inherit_from: .rubocop_todo.yml

require: rubocop-sketchup

AllCops:
  SketchUp:
    SourcePath: src
    TargetSketchUpVersion: 2014
    SketchupPerformance:
      Exclude:
      - profiling/
      - tests/
    SketchupRequirements:
      Exclude:
      - profiling/
      - tests/
    SketchupSuggestions:
      Exclude:
      - profiling/
      - tests/
  TargetRubyVersion: 2.1 # Should have been 2.0 but RuboCop dropped support.

# This cop is mainly there to educate new API users about the existance of
# model.active_model.
SketchupSuggestions/ModelEntities:
  Enabled: false

# These files are only relevant for development environment. Not bothering with
# Ruby encoding issues here.
SketchupSuggestions/FileEncoding:
  Exclude:
  - src/tt_shadow_texture/debugging/benchmark.rb
  - src/tt_shadow_texture/debugging/debug.rb
  - src/tt_shadow_texture/debugging/profiling.rb

# I will align my arrays as I please!
Layout/AlignArray:
  Enabled: false

# It's ok to use double empty lines for "paragraphs".
Layout/EmptyLines:
  Enabled: false

# Extra space is fine.
Layout/EmptyLinesAroundClassBody:
  Enabled: false

# Extra space is fine.
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# RuboCop - why you hate white-space?
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

# It's ok to have two empty lines to create "paragraphs".
Layout/EmptyLineBetweenDefs:
  NumberOfEmptyLines: [1, 2]

# Let git handle and normalize end of line. Eaiser for Windows.
Layout/EndOfLine:
  Enabled: false

# Spaces are fine to line up matrices etc to be more readable.
Layout/ExtraSpacing:
  Enabled: false

# This project use 4 spaces for continuity-lines.
Layout/IndentArray:
  Enabled: false

# This project use 4 spaces for continuity-lines.
Layout/IndentHash:
  Enabled: false

# Root extension file got an unusual indentation. That's fine.
# This is very particular to my TT::Plugin::Extension name scheme.
# Whoever might read this; the ::Plugin:: part is legacy naming I now regret.
Layout/IndentationWidth:
  Exclude:
    - 'src/*.rb'
    - 'profiling/PR_ShadowRender.rb'

# Spaces are fine to line up matrices etc to be more readable.
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

# Too noisy...
Metrics/AbcSize:
  Enabled: false

# Tests should have not upper size limit.
Metrics/ClassLength:
  Exclude:
    - 'profiling/**/*'
    - 'tests/**/*'
    - 'src/tt_shadow_texture/shadow_render_tool.rb' # TODO
    - 'src/tt_shadow_texture/image/bmp.rb' # TODO

# Too noisy...
Metrics/CyclomaticComplexity:
  Enabled: false

# Allowing for a few more lines than the default 10.
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'src/tt_shadow_texture/shadow_render_tool.rb' # TODO
    - 'src/tt_shadow_texture/image/bmp.rb' # TODO

# Too noisy...
Metrics/PerceivedComplexity:
  Enabled: false

# Tests follow a different naming convention.
Naming/ClassAndModuleCamelCase:
  Exclude:
    - 'profiling/**/*'
    - 'tests/**/*'

# Tests follow a different naming convention.
Naming/FileName:
  Exclude:
    - 'profiling/**/*'
    - 'tests/**/*'

# Tool classes must use the SketchUp API method names.
Naming/MethodName:
  Exclude:
    - '**/*_tool.rb'

# Variables such as x, y, z; u, v; r, g, b, is all too common within the world
# of 3D and their meaning is clear.
Naming/UncommunicativeMethodParamName:
  Enabled: false

# It's ok to use {...} for multi-line blocks.
Style/BlockDelimiters:
  Enabled: false

# Compact style is fine.
Style/ClassAndModuleChildren:
  Enabled: false

# Nah, it's ok.
Style/CommentedKeyword:
  Enabled: false

# No need for a doc-block for each class/module.
Style/Documentation:
  Enabled: false

# Some times it simply reads better to not have a modifier conditional.
Style/IfUnlessModifier:
  Enabled: false

# No need to force `.zero` over `== 0`
Style/NumericPredicate:
  Enabled: false

# It's fine to refer to self.
Style/RedundantSelf:
  Enabled: false

# It's fine to have trailing comma, makes adding/removing items easier.
Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
